// <auto-generated />
using System;
using FileService.Infrastructure.Postgres.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileService.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260204164418_Add SoftDelete")]
    partial class AddSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileService.Domain.Entites.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("StatusMedia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("asset_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("MediaAsset", (string)null);

                    b.HasDiscriminator<string>("asset_type").HasValue("MediaAsset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FileService.Domain.Entites.PreviewAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Entites.MediaAsset");

                    b.HasDiscriminator().HasValue("PreviewAsset");
                });

            modelBuilder.Entity("FileService.Domain.Entites.VideoAsset", b =>
                {
                    b.HasBaseType("FileService.Domain.Entites.MediaAsset");

                    b.HasDiscriminator().HasValue("VideoAsset");
                });

            modelBuilder.Entity("FileService.Domain.Entites.MediaAsset", b =>
                {
                    b.OwnsOne("FileService.Domain.VO.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ExpectedChunksCount")
                                .HasColumnType("integer");

                            b1.Property<long>("Size")
                                .HasColumnType("bigint");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("MediaAsset");

                            b1
                                .ToJson("MediaData")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FileService.Domain.VO.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("MediaType")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ValueContentType")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("MediaAsset");

                                    b2
                                        .ToJson("ContentType")
                                        .HasColumnType("jsonb");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FileService.Domain.VO.FiilName", "FiilName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Extention")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ValueName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("MediaAsset");

                                    b2
                                        .ToJson("FiilName")
                                        .HasColumnType("jsonb");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FiilName")
                                .IsRequired();
                        });

                    b.OwnsOne("FileService.Domain.VO.MediaOwner", "Owner", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("EntiteId")
                                .HasColumnType("uuid");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("MediaAsset");

                            b1
                                .ToJson("Owner")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.OwnsOne("FileService.Domain.VO.StorageKey", "Key", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bucket")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FullPath")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Prefix")
                                .HasColumnType("text");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("MediaAsset");

                            b1
                                .ToJson("Key")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.Navigation("Key")
                        .IsRequired();

                    b.Navigation("MediaData")
                        .IsRequired();

                    b.Navigation("Owner")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
